In [ ]:
# ALGORITMO 2 DEL KG 

def _kg2(x, optimizer, gp, y_max):
        def posterior(gp, x_obs, y_obs, grid):
            gp.fit(x_obs, y_obs)
            mu, sigma = gp.predict(grid, return_std=True)
            return mu

        #print(optimizer.res)
        list_diff = []
        x_obs = np.array([[res["params"]["x"]] for res in optimizer.res])
        y_obs = np.array([res["target"] for res in optimizer.res])
        # print(x_obs)
        
        
        init = [np.zeros(1000)]*2
        n = optimizer._space.bounds.shape[0]
        
        # DUE DIMENSIONI
        if (n > 1):
            for(i in range(2)): 
                init[i] = np.linspace(optimizer._space.bounds[i,0], optimizer._space.bounds[i,1], 1000)
            
            grid = np.meshgrid(init[0], init[1])   
            grid = np.array(grid)
            grid = grid.reshape(-1,2)
            
            J = 10 

            for j in range(J):
                mean_n1star=np.zeros(len(x))
                diff=np.zeros(len(x))
                ii=0
                print(j+1) # number of iteration
                for i in x:
                    with warnings.catch_warnings():
                        warnings.simplefilter("ignore")
                        # otteniamo la current mean e std per samplare il nuovo y
                        mean, std= gp.predict(i, return_std=True)
                        # sample il nuovo y
                        y=random.normal(loc=mean, scale=std)
                        # aggiungi la coppia (i, y) ai vettori del GP
                        x_newobs=np.append(x_obs, i)
                        y_newobs=np.append(y_obs,y).reshape(-1,1)
                        # re-fittiamo il gaussian process e calcoliamo il massimo valore della nuova media
                        mu=posterior(gp, x_newobs, y_newobs, grid)
                        mean_n1star[ii]= max(mu)
                        #con minimize è troppo lento
                        #mean_n1star[ii] = minimize(lambda t: -posterior(optimizer, x_newobs, y_newobs, t.reshape(-1,1))[0],
                                                   #init.reshape(-1, 1),
                                                   #method="L-BFGS-B")['fun']
                        # diff è un vettore di lunghezza uguale alla lunghezza di x
                        diff[ii] = (mean_n1star[ii]-mean_nstar)
                        ii=ii+1
                # a è una lista di vettori
                list_diff.append(diff)

            # calcoliamo la MCMC stima per ciascuna componente    
            sum_list_diff=0 
            for array in list_diff:
                sum_list_diff += array

            out = sum_list_diff/J
            print(len(out))
            return(out)
        
        
        
        # In una dimensione (codice che avevamo già scritto)
        else:
            grid = np.linspace(min(x), max(x), 1000)
            grid = grid.reshape(-1,1)
            mean_nstar = max(posterior(gp, x_obs, y_obs, grid))
            #print(mean_nstar['fun'])
            J = 10 

            for j in range(J):
                mean_n1star=np.zeros(len(x))
                diff=np.zeros(len(x))
                ii=0
                print(j+1) # number of iteration
                for i in x:
                    with warnings.catch_warnings():
                        warnings.simplefilter("ignore")
                        # otteniamo la current mean e std per samplare il nuovo y
                        mean, std= gp.predict(i.reshape(1,-1), return_std=True)
                        # sample il nuovo y
                        y=random.normal(loc=mean, scale=std)
                        # aggiungi la coppia (i, y) ai vettori del GP
                        x_newobs=np.append(x_obs, i).reshape(-1,1)
                        y_newobs=np.append(y_obs,y).reshape(-1,1)
                        # re-fittiamo il gaussian process e calcoliamo il massimo valore della nuova media
                        mu=posterior(gp, x_newobs, y_newobs, grid)
                        mean_n1star[ii]= max(mu)
                        #con minimize è troppo lento
                        #mean_n1star[ii] = minimize(lambda t: -posterior(optimizer, x_newobs, y_newobs, t.reshape(-1,1))[0],
                                                   #init.reshape(-1, 1),
                                                   #method="L-BFGS-B")['fun']
                        # diff è un vettore di lunghezza uguale alla lunghezza di x
                        diff[ii] = (mean_n1star[ii]-mean_nstar)
                        ii=ii+1
                # a è una lista di vettori
                list_diff.append(diff)

            # calcoliamo la MCMC stima per ciascuna componente    
            sum_list_diff=0 
            for array in list_diff:
                sum_list_diff += array

            out = sum_list_diff/J
            print(len(out))
            return(out)

        
        

In [19]:
import numpy as np
X,Y = np.mgrid[-5:5.1, -5:5.1]

In [21]:
#print(X)
print(X)

[[-5. -5. -5. -5. -5. -5. -5. -5. -5. -5. -5.]
 [-4. -4. -4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]]


In [25]:
x1=X[1]
x2=X[2]
min(x1,x2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
[i,1]