In [1]:
import sys
import os 
# current working directory
path = os.getcwd()
# parent directory
parent = os.path.join(path, os.pardir)
sys.path.append(os.path.abspath(parent))
from bayes_opt1 import BayesianOptimization
from bayes_opt1 import UtilityFunction
import numpy as np

import matplotlib.pyplot as plt
from matplotlib import gridspec
%matplotlib inline

from scipy.stats import norm
from scipy.optimize import minimize

import random
import warnings
from pyDOE import lhs # for Latin Hypercube Design
import numdifftools as nd # for Algorithm 4 (gradient computation)

In [2]:
# Runnare per installare le librerie nuove:

# pip install pyDOE
# pip install numdifftools

# Test 1D

In [3]:
# Let's start by definying our function, bounds, and instanciating an optimization object.
def black_box_function(x):
    return np.exp(-(x - 2)**2) + np.exp(-(x - 6)**2/10) + 1/ (x**2 + 1)

x = np.linspace(-2, 10, 10) # NO reshape
# x needs to be an array of shape (something,)

optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds={'x': (-2, 10)},
    verbose=2,
    random_state=1,
)
optimizer.maximize(init_points=2, n_iter=0, kappa=5, acq='kg')
optimizer.maximize(init_points=0, n_iter=2, kappa=5, acq='kg')

|   iter    |  target   |     x     |
-------------------------------------
|  1        |  0.8721   |  3.004    |
|  2        |  0.9815   |  6.644    |
|   iter    |  target   |     x     |
-------------------------------------
j =  1
j =  2
j =  3
j =  4
j =  5
j =  1
j =  2
j =  3
j =  4
j =  5
j =  1
j =  2
j =  3
j =  4
j =  5
j =  1
j =  2
j =  3
j =  4
j =  5


/Users/martina/opt/anaconda3/lib/python3.8/site-packages/sklearn/gaussian_process/kernels.py:402: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn("The optimal value found for "


j =  1
j =  2
j =  3
j =  4
j =  5


/Users/martina/opt/anaconda3/lib/python3.8/site-packages/sklearn/gaussian_process/kernels.py:402: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn("The optimal value found for "


1
|  3        |  1.034    |  0.2092   |


/Users/martina/opt/anaconda3/lib/python3.8/site-packages/sklearn/gaussian_process/kernels.py:402: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn("The optimal value found for "


j =  1
j =  2
j =  3
j =  4
j =  5
j =  1
j =  2
j =  3
j =  4
j =  5
j =  1
j =  2
j =  3
j =  4
j =  5
j =  1
j =  2
j =  3
j =  4
j =  5


/Users/martina/opt/anaconda3/lib/python3.8/site-packages/sklearn/gaussian_process/kernels.py:402: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn("The optimal value found for "


j =  1
j =  2
j =  3
j =  4
j =  5
1
|  4        |  1.226    |  1.512    |


/Users/martina/opt/anaconda3/lib/python3.8/site-packages/sklearn/gaussian_process/kernels.py:402: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn("The optimal value found for "


In [4]:
# UCB
optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds={'x': (-2, 10)},
    verbose=2,
    random_state=1,
)
optimizer.maximize(init_points=2, n_iter=0, kappa=5, acq='ucb')
optimizer.maximize(init_points=0, n_iter=2, kappa=5, acq='ucb')

|   iter    |  target   |     x     |
-------------------------------------
|  1        |  0.8721   |  3.004    |
|  2        |  0.9815   |  6.644    |
|   iter    |  target   |     x     |
-------------------------------------
|  3        |  1.009    |  6.383    |
|  4        |  0.9802   |  5.249    |


# Test 2D

In [5]:
# Let's start by definying our function, bounds, and instanciating an optimization object.
def black_box_function(x, y):
    return -x ** 2 - (y - 1) ** 2 + 1
optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds={'x': (-2, -1), 'y': (2, 3)},
    verbose=2,
    random_state=1,
)
optimizer.maximize(init_points=2, n_iter=0, kappa=5, acq='kg')
optimizer.maximize(init_points=0, n_iter=1, kappa=5, acq='kg')

|   iter    |  target   |     x     |     y     |
-------------------------------------------------
|  1        | -4.465    | -1.583    |  2.72     |
|  2        | -4.696    | -2.0      |  2.302    |
|   iter    |  target   |     x     |     y     |
-------------------------------------------------
[[-1.04427459  2.17388857]]
j =  1
j =  2
j =  3
j =  4
j =  5
[[-0.86608586  2.17963439]]
j =  1
j =  2
j =  3
j =  4
j =  5
[[-0.80470624  1.79104939]]
j =  1
j =  2
j =  3
j =  4
j =  5
[[-0.76387126  2.01787894]]
j =  1
j =  2
j =  3
j =  4
j =  5
[[-0.57079753  2.02567065]]
j =  1
j =  2
j =  3
j =  4
j =  5
1
|  3        | -1.469    | -1.044    |  2.174    |


In [6]:
# EI
optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds={'x': (-2, -1), 'y': (2, 3)},
    verbose=2,
    random_state=1,
)
optimizer.maximize(init_points=2, n_iter=0, kappa=5, acq='ei')
optimizer.maximize(init_points=0, n_iter=1, kappa=5, acq='ei')

|   iter    |  target   |     x     |     y     |
-------------------------------------------------
|  1        | -4.465    | -1.583    |  2.72     |
|  2        | -4.696    | -2.0      |  2.302    |
|   iter    |  target   |     x     |     y     |
-------------------------------------------------
|  3        | -4.488    | -1.585    |  2.725    |


# Test 5D

In [ ]:
# Let's start by definying our function, bounds, and instanciating an optimization object.
def black_box_function(x1, x2, x3, x4, x5):
    return -x1 ** 2 - (x2 - 1) ** 2 + 1 + x3 + x4 + x5

Moooolto lento con KG: bisogna diminuire n_grid

In [ ]:
optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds={'x1': (-2, -1), 'x2': (2, 3), 'x3': (2, 3), 'x4': (2, 3), 'x5': (2, 3)},
    verbose=2,
    random_state=1,
)
optimizer.maximize(init_points=2, n_iter=0, kappa=5, acq='kg')
optimizer.maximize(init_points=0, n_iter=1, kappa=5, acq='kg')

In [ ]:
# Poi
optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds={'x1': (-2, -1), 'x2': (2, 3), 'x3': (2, 3), 'x4': (2, 3), 'x5': (2, 3)},
    verbose=2,
    random_state=1,
)
optimizer.maximize(init_points=2, n_iter=0, kappa=5, acq='poi')
optimizer.maximize(init_points=0, n_iter=1, kappa=5, acq='poi')